<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>deleteresume</name>
   <tag></tag>
   <elementGuidId>1dc54075-7a3a-453f-9cd5-50c503e17865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[data-fn='deleteCv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[data-fn='deleteCv']</value>
   </webElementProperties>
</WebElementEntity>
