<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uploadCvLink</name>
   <tag></tag>
   <elementGuidId>e9218c16-10f3-40a2-9c1b-c8a0181cd22f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[data-efctype='cvUpload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[data-efctype='cvUpload']</value>
   </webElementProperties>
</WebElementEntity>
