<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Password</description>
   <name>Password</name>
   <tag></tag>
   <elementGuidId>d73d8df1-2c98-4b3e-a4b6-adea71017b61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[name='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[name='password']</value>
   </webElementProperties>
</WebElementEntity>
