<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>UserName</description>
   <name>UserName</name>
   <tag></tag>
   <elementGuidId>fdf68fd6-c685-430e-985c-921600c4124f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[name='email']</value>
   </webElementProperties>
</WebElementEntity>
