<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iPlayerLogo</name>
   <tag></tag>
   <elementGuidId>3588ec25-d2ac-4dff-98c0-429d12c6e848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.ipNav__logo__link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.ipNav__logo__link</value>
   </webElementProperties>
</WebElementEntity>
