<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SportLogo</name>
   <tag></tag>
   <elementGuidId>1d5183e4-9357-4981-a793-7e0572aea981</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.sp-c-global-header__logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.sp-c-global-header__logo</value>
   </webElementProperties>
</WebElementEntity>
